### ISSUE TITLE
T95 Max support, distro recommendations

### ISSUE THREAD

**Issue by danboid** [ktkd/linux-5.7-h6-mainline#2]
Thanks for working on supporting the Allwinner H6 TV boxes under Linux!

I have ordered a T95 Max that I wish to install Linux on. Can you recommend any pre-built Linux distro images for the T95 Max? I normally prefer to run Arch (ALARM) or Debuntu (Armbian) but I'd imagine there aren't that many choices out there for these TV boxes and it seems Armbian and ALARM do not (officially) support them.

If there are no good pre-built images, is there a guide to creating a bootable image or installer for these H6 TV boxes, specifically the T95 Max?

Have these patches been upstreamed into the kernel? If not, why not?

I'm not new to (ARM) Linux but I'm not a kernel dev so it would be nice to get a few tips. My searches haven't been very successful.

**Comment by ktkd** [comment]
hello, most of this patches are already in mainline kernel. think you need look to sunxi-linux maillist's and https://linux-sunxi.org/Linux_mainlining_effort, also read  how to build armbian images with armbian build system.
ps. only one difference between t95 and tanix tx6 is another keymap on remote. hope this helps you :)

**Comment by danboid** [comment]
Thanks for your info ktkd, that is useful to know about the keymap.

I found this video that explains the process of installing Armbian on a Tanix TX6, although the comments indicate it has changed in recent Armbian releases. I'm sure it will be a very similar process for the T95 Max.

https://www.youtube.com/watch?v=XCNBPoVE_m4
